### ISSUE TITLE
Optimism-default (promote Optimism within synpress)

### ISSUE THREAD

**Issue by drptbl** [Synthetixio/synpress#722]
**Description:**
We plan to enhance the visibility and accessibility of the Optimism network by making it the default setting for Synpress. This will be a pivotal step towards garnering increased attention and usage of the network. Additionally, we aim to optimize the user experience by updating and refining the existing Synpress examples to ensure seamless integration with Optimism and streamline the onboarding process for our users.

**Tasks:**
- [x] Add `Optimism` network to synpress
- [x] Add `Optimism Goerli` network to synpress
- [x] Set `Optimism` network (mainnet) as default
- [x] Check if [@metamask/test-dapp](https://www.npmjs.com/package/@metamask/test-dapp) works with `Optimism Goerli`
- [ ] Update [synpress-examples](https://github.com/drptbl/synpress-examples) to use `Optimism Goerli`
- [ ] Update [synpress internal e2e tests](https://github.com/Synthetixio/synpress/tree/dev/tests/e2e) to use forked (with anvil) `Optimism Goerli` (optional)
- [x] Add `Optimism` logo to `Sponsored & used by` section inside [README.md](https://github.com/Synthetixio/synpress#readme)
